
export const GET_SHIPPING_ADDRESS = "GET_SHIPPING_ADDRESS";
export const GET_BILLING_ADDRESS = "GET_BILLING_ADDRESS";
export const CHANGE_BILLING_ADDRESS_INPUT = "CHANGE_BILLING_ADDRESS_INPUT";
export const CHANGE_SHIPPING_ADDRESS_INPUT = "CHANGE_SHIPPING_ADDRESS_INPUT";
export const CHANGE_USER_INPUT_DATA = "CHANGE_USER_INPUT_DATA";
export const UPDATED_USER_DATA = "UPDATED_USER_DATA";
export const GET_USER_UPDATED_DATA = "GET_USER_UPDATED_DATA";
export const GET_COUNTRIES_LIST = "GET_COUNTRIES_LIST";
export const GET_DIVISIONS_LIST = "GET_DIVISIONS_LIST";
export const GET_CITIES_LIST = "GET_CITIES_LIST";
export const GET_AREA_LIST = "GET_AREA_LIST";
export const STORE_BILLING_ADDRESS = "STORE_BILLING_ADDRESS";
export const STORE_SHIPPING_ADDRESS = "STORE_SHIPPING_ADDRESS";

export const GET_SINGLE_ADDRESS = "GET_SINGLE_ADDRESS";
export const CHANGE_ADDRESS_INPUT = "CHANGE_ADDRESS_INPUT";
export const EMPTY_DISPATCH = "EMPTY_DISPATCH";
export const DELETE_ADDRESS = "DELETE_ADDRESS";

export const GET_DEFAULT_SHIPPING_ADDRESS = "GET_DEFAULT_SHIPPING_ADDRESS";
export const GET_DEFAULT_BILLING_ADDRESS = "GET_DEFAULT_BILLING_ADDRESS";
export const GET_SINGLE_SHIPPING_ADDRESS = "GET_SINGLE_SHIPPING_ADDRESS";
export const CHANGE_USER_PROFILE_INPUT_DATA = "CHANGE_USER_PROFILE_INPUT_DATA";

export const RESET_PROFILE_ACCOUNT_CITY_AREA = "RESET_PROFILE_ACCOUNT_CITY_AREA";