export const INIT_STORE_LIST = "INIT_STORE_LIST";
export const GET_STORE_LIST = "GET_STORE_LIST";
export const FETCH_STORE_LIST_FAILED = "FETCH_STORE_LIST_FAILED";

export const STORE_LOCATION_CLEARED = "STORE_LOCATION_CLEARED";
export const STORE_LOCATION_CHANGED = "STORE_LOCATION_CHANGED";