export const GET_CARTS                 = "GET_CARTS";
export const ADD_CART_DATA           = "ADD_CART_DATA";

export const GET_COMBINE_CARTS         = "GET_COMBINE_CARTS";
export const GET_CARTS_LOADING         = "GET_CARTS_LOADING";
export const POST_CARTS_LOADING        = "POST_CARTS_LOADING";
export const EMPTY_CART_MESSAGE        = "EMPTY_CART_MESSAGE";
export const EMPTY_CART_DELETE_MESSAGE = "EMPTY_CART_DELETE_MESSAGE";
export const UPDATE_CARTS_DATA         = "UPDATE_CARTS_DATA";
export const DELETE_CARTS_DATA         = "DELETE_CARTS_DATA";

//coupon
export const CHANGE_COUPON_INPUT_DATA  = "CHANGE_COUPON_INPUT_DATA";
export const APPLY_COUPON_CODE         = "APPLY_COUPON_CODE";
export const APPLY_SHIPPING_COST       = "APPLY_SHIPPING_COST";

// order types
export const ORDER_SUBMIT = "ORDER_SUBMIT"
export const GET_USER_ORDER_LIST = "GET_MY_ORDER_LIST";
export const GET_ORDER_FILTER_OPTION_DATA = "GET_ORDER_FILTER_OPTION_DATA";
export const GET_TRACKING_TIMELINE_DATA = "GET_TRACKING_TIMELINE_DATA";
export const CANCEL_ORDER = "CANCEL_ORDER";
export const GET_ORDER_DETAILS = "GET_ORDER_DETAILS";
export const GET_ORDER_LIFECYCLE_DETAILS = "GET_ORDER_LIFECYCLE_DETAILS";