export const CHECK_EMAIL_STATUS = "CHECK_EMAIL_STATUS";
export const VALIDATE_OTP = "VALIDATE_OTP";
export const POST_RESET_PASSWORD = "POST_RESET_PASSWORD";
export const SUCCESSFULLY_RESET_PASSWORD = "SUCCESSFULLY_RESET_PASSWORD";
export const RESET_PASSWORD_FAILED = "RESET_PASSWORD_FAILED";