export const INIT_BANNER_CAROUSEL_LIST = "INIT_BANNER_CAROUSEL_LIST";
export const GET_BANNER_CAROUSEL_LIST = "GET_BANNER_CAROUSEL_LIST";
export const FETCH_BANNER_CAROUSEL_LIST_FAILED = "FETCH_BANNER_CAROUSEL_LIST_FAILED";