export const TOGGLE_MODAL = "TOGGLE_MODAL";
export const TOGGLE_FLOATING_CART = "TOGGLE_FLOATING_CART";

export const GET_DEVICE_INFO = "GET_DEVICE_INFO";

export const TOGGLE_BACKDROP = "TOGGLE_BACKDROP";

export const IS_SIGNED_IN = "IS_SIGNED_IN";

export const SET_WELCOME_POPUP = "SET_WELCOME_POPUP";