
export const GET_CATEGORIES = "GET_CATEGORIES";
export const GET_SUB_CATEGORY = "GET_SUB_CATEGORY";

export const GET_CATEGORY_WISE_PRODUCT_LIST = "GET_CATEGORY_WISE_PRODUCT_LIST";

export const INIT_PRODUCT_LIST = "INIT_PRODUCT_LIST";
export const GET_PRODUCT_LIST_FAILED = "GET_PRODUCT_LIST_FAILED";

export const INIT_FILTER_PRODUCT_LIST = "INIT_FILTER_PRODUCT_LIST";
export const GET_FILTER_PRODUCT_LIST = "GET_FILTER_PRODUCT_LIST";
export const GET_FILTER_PRODUCT_LIST_FAILED = "GET_FILTER_PRODUCT_LIST_FAILED";

export const SET_FILTER_PARAM = "SET_FILTER_PARAM";
export const RESET_FILTER_PARAM = "RESET_FILTER_PARAM";

export const GET_CATEGORY_OR_BRAND_DETAILS = "GET_CATEGORY_OR_BRAND_DETAILS";

export const GET_CATEGORY_RELATED_BRANDS = "GET_CATEGORY_RELATED_BRANDS";
