export const GET_ITEM_LIST_BY_USER = "GET_ITEM_LIST_BY_USER";
export const GET_REVIEW_LIST_BY_USER = "GET_REVIEW_LIST_BY_USER";
export const CHANGE_REVIEW_INPUT = "CHANGE_REVIEW_INPUT";
export const STORE_REVIEW_DATA = "STORE_REVIEW_DATA";